### ISSUE TITLE
Exportable Environment Variables

### ISSUE THREAD

**Issue by bramwelt** [mozilla/configman#117]
In order to use configman in Socorro, the `env` command is required because the configuration keys contain periods. This prevents us from exporting environment variables in the shell.

One way this could work is if configuration options were guaranteed to be unique and shell counterparts did not contain invalid characters such as `.` or `-`. Each config option could have periods replaced by underscores, and underscores in the name replaced by double-underscores.

**Comment by twobraids** [comment]
this issue was addressed long ago.  re-open if anyone disagrees.
