### ISSUE TITLE
better bool parsing

### ISSUE THREAD

**Issue by willkg** [mozilla/configman#165]
The configman docs say to use the Python bool built-in for converting configuration values into bools. I don't think that's particularly helpful. What happens is an empty string becomes False and any non-empty string--including "False"--becomes True. Further, that's totally not obvious from the configman documentation especially in light of how other configuration libraries provide their own bool parser that's more helpful.

I think we have a few options here:

1. implement a `bool_converter` function and document how that should be used instead of the Python builtin
2. fix the documentation so that it's clearer what the `bool` built-in does and provide a lambda alternative depending on the user's needs
3. not worry about it

I'm inclined to go with number 1, but I don't know what the spirit of configman would suggest.

Thoughts?

**Comment by adngdb** [comment]
The converter already exists: https://github.com/mozilla/configman/blob/master/configman/converters.py#L127

So I would go with number 1, but just the documentation part. :)

**Comment by willkg** [comment]
Ahh... Awesome! I'll fix the docs, then. Thank you!
